### ISSUE TITLE
Error while updating stats, it seems to be a firewall that blocking the stats

### ISSUE THREAD

**Issue by eereeska** [Elikill58/Negativity#106]
**Your plugin version**
1.6

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.14.4

**Error / Logs**
https://pastebin.com/p95YVHVX

Also please add option to disable this message:
WARN McLeaks API seem to be down. So, we cannot know if the player is using it.

I dont want see it every time when player has joined.

**Comment by Elikill58** [comment]
The error and the warn message doesn't come from the same problem.
Both "Error while updating stats, it seems to be a firewall that blocking the stats" are coming because of McLeaks API as you said.
But, for the error it's because my stats server was down. Now, it must be UP.

I'm waiting the confirmation for the new state, i will close it tomorrow without response.

Note: Everyday, a 5:00, my stats server restart.

**Comment by Elikill58** [comment]
"I'm waiting the confirmation for the new state, i will close it tomorrow without response." I close this issue.
No other problem reported, the server seem to be always UP.
