### ISSUE TITLE
Using shift click to move multiple stacks of something triggers autosteal in the ~70% range.

### ISSUE THREAD

**Issue by SnowyDwarf** [Elikill58/Negativity#198]
**Describe the bug**
see title, specifically triggered on stone axes

**Your plugin version**
v2

**Your platform version (and precise the platforme (spigot/sponge))**
PaperSpigot 1.16.3 build #212

**Comment by spetznack** [comment]
Confirmed on Negativity_v2 16.10.2020

Also happens when using clientside mods to sort and move things between the open container. But this is maybe partially what this check is designed to prevent? o.o

Proof output: 
https://gist.github.com/spetznack/73bc3729f235205e28080aca5ef22a8d

Screenshot: 
![AutoSteal false-positive when shift-clicking to move items tofrom chests or other containers](https://user-images.githubusercontent.com/1935616/96605243-3f688000-12f6-11eb-927f-0198aeadea40.gif)
