### ISSUE TITLE
New permission to prevent a person with negativity.admin from disturbing another.

### ISSUE THREAD

**Issue by R4f4Lc** [Elikill58/Negativity#203]
It's about :
- [x] Other

**Explain the feature that you want**
Anyone with the negativity.admin permission can for example freeze someone else who has the negativity.admin permission.
Add a permit that prevents you from freezing, viewing inventory, etc. of the person who has it.

**Additional context**
A moderator who wants to annoy other moderators can freeze the rest.

**Comment by Elikill58** [comment]
Yes, that's a good idea and for me, it's important.
Do you think that I have to prevent mod to freeze other mod ?

**Comment by R4f4Lc** [comment]
Yes, on my server an old moderator was bothering the rest by freezing and leaving them unable to do anything. I would add a permission called negativity.bypass that prevents you from being frozen, etc.

**Comment by spetznack** [comment]
In my opinion mods should be allowed to open other moderator's inventories by default because in some cases it can be useful, for the freeze I don't have a preference. 
So if you have negativity.admin then it will by default give you negativity.admin.inventory.otheradmins or whatever. 


**You are supposed to be able to trust your moderators you know..** 
When your bartender is pickpocketing you in your own bar, the solution is not to use zipperpockets so the bartender can no longer pickpocket you. It might solve the problem for you but who will the bartender pickpocket next? your customers? 
Erm.. weird analogy I know, but the point I am getting at is that you should probably let your moderators know that they are not supposed to use their powers unless there is a situation that requires moderator attention..

**Comment by Elikill58** [comment]
The bypass permission will be for v2, for v1 it's only a non-authorization if the other have negativity.admin ...
