### ISSUE TITLE
Support Anti World Downloaders.

### ISSUE THREAD

**Issue by FurryOfficial** [Elikill58/Negativity#259]
**It's about :**
- [ ] A translation
- [ ] A new plugin support
- [x] New detection: Anti WDL
- [ ] Other

**Explain the feature that you want**
Prevent people using World Downloader mods or client. This feature will make the server much more safer, protect the buildings and the map.

**Additional context**
![image](https://user-images.githubusercontent.com/70711319/119092194-514f0480-ba38-11eb-9703-4d871ba331d9.png)
![image](https://user-images.githubusercontent.com/70711319/119092257-69bf1f00-ba38-11eb-920a-822ed22c35dd.png)

**Comment by mpfaff** [comment]
How would this work? Would it just be detecting specific mods? Or would it detect the actual behaviour? I feel like if it would just be detecting specific mods it is kind of pointless, because someone who actually cares will just use VanillaSpoof. On the other hand, such a module would likely prevent all lazy copiers, so perhaps it does have some use.

**Comment by Elikill58** [comment]
When Furry create the issue, I make some search. The cheat seems to use a specific packet which is used to get the world where the player will be.
So, I have to detect when the player try to download the world like he just connect, but he is online since few minutes.

It already exist plugin who do it, but mostly are not compatible with 1.15 & more.

**Comment by mpfaff** [comment]
Interesting. That certainly seems doable, but wouldn't the it bypass just by using the same packet as vanilla at the time of connection instead? Also, wouldn't it also work just by using loaded chunks like the Litematica mod?

**Comment by Elikill58** [comment]
I don't know yet, It few questions that I will be able to reply after testing
