### ISSUE TITLE
Option to edit new version message

### ISSUE THREAD

**Issue by Kruize1** [Elikill58/Negativity#266]
**It's about :**
- [ ] A translation
- [ ] A new plugin support
- [ ] New detection
- [x] Other

**Explain the feature that you want**
I want an option to disable this message and change the message that appears
![image](https://user-images.githubusercontent.com/21042824/121760680-e6499880-cae0-11eb-89e2-63705e191eeb.png)

**Additional context**
- 1 option to disable message
- 1 option to change locale text strings

**Comment by Elikill58** [comment]
No, it will not be possible to disable this message. Why ?

It's an anticheat. For others types of plugins, it's not a pitty. But for us, making update is necessary. Also, it's to prevent "here is false flag" but it's fixed in update ...

So it's not in my mind now to allow disabling this message.

Changing his text is good suggestion !
