### ISSUE TITLE
Bypass with Rise Client - Step

### ISSUE THREAD

**Issue by dejwideek-dev** [Elikill58/Negativity#307]
**Modes:**
- [x] timer
- [x] matrix
- [x] hypixel (speed: 2.2)
- [ ] normal
- [x] low
- [x] delay
- [x] low2
- [x] low3

**Comment by Elikill58** [comment]
- Hypixel is already detected (seems since new dev build detection)
- low, low2, low3, timer, matrix and delay seems to don't create specific avantage according to other players (can't go upper than 1 block, such as legit client)
In conclusion: Except NCP, there isn't height config to go upper than 1 block, so this step cheat seems broken, useless or just bad.
