### ISSUE TITLE
Reload does nothing

### ISSUE THREAD

**Issue by Katrix** [Elikill58/Negativity#50]
**Describe the bug**
The reload command does nothing

**Your plugin version**
1.5

**Your platform version (and precise the platforme (spigot/sponge))**
1.14 Spigot

**Additional context**
I get autocomplete fine, and it complains about an invalid command if I mistype it, but no indication that anything happened if I run the actual reload command. The old config also continues to be in effect.

**Comment by RedNesto** [comment]
Hi, I was aware of this issue and already made a fix for it but forgot to commit it for the 1.5.

I'll push the fix soon and it will be in the next minor version, thanks for reminding me of this bug.

**Comment by RedNesto** [comment]
Also about the absence of feedback after a successful reload it, bothers me too. Some time ago I went through all the commands of the Spigot plugin to improve the UX (including this feedback problem), tab completion and to remove duplication, but there's been a bunch of changes since then.

I'll rebase that branch and see with Elikill to get it merged for the next version.
